/**
 * Country App URLs Configuration
 * 
 * Add your country app URLs here. Format:
 * "Country Name": "https://your-app-url.com"
 * 
 * Leave as empty string "" to disable a country
 * Set to a URL to enable it
 */

const COUNTRY_URLS = {
    "Algeria": "",
    "Angola": "",
    "Argentina": "",
    "Australia": "https://ausstd.officestoolsai.com/", // Australia app URL
    "Austria": "",
    "Bahrain": "",
    "Bangladesh": "",
    "Belgium": "",
    "Bolivia": "",
    "Bosnia & Herzegovina": "",
    "Botswana": "",
    "Brunei": "",
    "Bulgaria": "",
    "Cambodia": "",
    "Canada": "",
    "Chile": "",
    "China": "",
    "Colombia": "",
    "Costa Rica": "",
    "Côte d'Ivoire": "",
    "Croatia": "",
    "Cyprus": "",
    "Czech Republic": "",
    "Denmark": "",
    "Dominican Republic": "",
    "Ecuador": "",
    "Egypt": "",
    "El Salvador": "",
    "Estonia": "",
    "Ethiopia": "",
    "Finland": "",
    "France": "",
    "Germany": "",
    "Ghana": "",
    "Greece": "",
    "Guatemala": "",
    "Hong Kong": "",
    "Honduras": "",
    "Hungary": "",
    "Iceland": "",
    "India": "",
    "Indonesia": "",
    "Iran": "",
    "Ireland": "",
    "Israel": "",
    "Italy": "",
    "Jamaica": "",
    "Japan": "",
    "Jordan": "",
    "Kazakhstan": "",
    "Kenya": "",
    "Kuwait": "",
    "Latvia": "",
    "Lebanon": "",
    "Lithuania": "",
    "Luxembourg": "",
    "Malaysia": "",
    "Mexico": "",
    "Mongolia": "",
    "Morocco": "",
    "Myanmar": "",
    "Namibia": "",
    "Nepal": "",
    "Netherlands": "",
    "New Zealand": "",
    "Nigeria": "",
    "Norway": "",
    "Oman": "",
    "Pakistan": "",
    "Panama": "",
    "Paraguay": "",
    "Peru": "",
    "Philippines": "",
    "Poland": "",
    "Portugal": "",
    "Qatar": "",
    "Romania": "",
    "Russia": "",
    "Saudi Arabia": "",
    "Serbia": "",
    "Singapore": "",
    "Slovakia": "",
    "Slovenia": "",
    "South Africa": "",
    "South Korea": "",
    "Spain": "",
    "Sri Lanka": "",
    "Sweden": "",
    "Switzerland": "",
    "Taiwan": "",
    "Tanzania": "",
    "Thailand": "",
    "Trinidad & Tobago": "",
    "Tunisia": "",
    "Turkey": "",
    "Ukraine": "",
    "United Arab Emirates": "",
    "United Kingdom": "",
    "United States": "",
    "Uruguay": "",
    "Vietnam": ""
};

// Verify the config is loaded
if (typeof COUNTRY_URLS !== 'undefined') {
    console.log('Country URLs config loaded successfully');
} else {
    console.error('Country URLs config failed to load');
}

